### PR TITLE
Upgrade Avalonia version

### PR DESCRIPTION
**Pull request by rstm-sf**
Upgrade Avalonia version

Resolve
>  make `FormulaBlock` public

in TODO list https://github.com/ForNeVeR/wpf-math/issues/17#issuecomment-453836924

picture

### CODE REVIEW

**Comment by rstm-sf** [comment]
> C:\Users\appveyor\.nuget\packages\avalonia\0.9.2\build\AvaloniaBuildTasks.targets(63,5): error MSB4062: The "CompileAvaloniaXamlTask" task could not be loaded from the assembly C:\Users\appveyor\.nuget\packages\avalonia\0.9.2\build\\..\tools\netstandard2.0\Avalonia.Build.Tasks.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\projects\wpf-math\src\AvaloniaMath.Example\AvaloniaMath.Example.csproj]
https://ci.appveyor.com/project/ForNeVeR/wpf-math/builds/30360629#L124

**Comment by rstm-sf** [comment]
The error is the same as here fsprojects/Paket#2849

**Comment by rstm-sf** [comment]
Ok I give up, but this should be decided by restarting or in another way that I don’t know

**Comment by ForNeVeR** [comment]
Let me try some things.

**Comment by rstm-sf** [comment]
> Let me try some things.

Ok, no problem

**Comment by ForNeVeR** [comment]
Okay, the build issue has been fixed.

**Comment by ForNeVeR** [comment]
@rstm-sf, thanks for help!

**Pull request merged**
