### PR TITLE
Added bezier curves instead of flattening geometry for svg

### PR DESCRIPTION
**Pull request by nocturnals**
Added support for drawing bezier curves when exporting to svg
fixed a small mistake I made in the original code: used Points[0] as starting point in polyline instead of StartPoint.

### CODE REVIEW

**Comment by gsomix** [comment]
@nocturnals Hi! Could you elaborate a little why this PR is closed?

**Comment by nocturnals** [comment]
I've did a PR too soon and noticed there was a mistake in the code. I think it's ok now but I'm going to experiment a bit before to make sure everything works before issuing another PR.

**Comment by gsomix** [comment]
@nocturnals OK, firstly thanks for PR! You actually don't need to close PR, just mark it [Work In Progress] in label if it's not ready yet.

**Comment by ForNeVeR** [comment]
@nocturnals hello and thanks for your contribution. Here're some general notes on our workflow regarding pull requests:

1. It's okay to create PR and mark it as "[WIP]" / "[Work in Progress]" if you're still working on it, if you want the maintainers to review your work while you're still on it.
2. It's generally recommended to create new git branch (e.g. `svg-fixes`) and send PR from it instead of sending a PR directly from `master` branch, because...
3. Pull requests aren't immutable. You can always update your pull request by pushing / force-pushing commits to the pull request branch.

Also, I'm curious, you said
> fixed a small mistake I made in the original code

Does that mean the you're the original code author? Does that mean you're Marc Palmans?

**Comment by ForNeVeR** [comment]
Aha, I've checked the commit log. You really are Marc Palmans. It's great to meet you. Welcome aboard!

**Pull request closed without merging**
