### PR TITLE
Added a file for logging errors

### PR DESCRIPTION
**Pull request by B3zaleel**

### CODE REVIEW

**Comment by ForNeVeR** [comment]
I don't understand what's the use of this class. It is `public`, so it's probably indended for the library users.

I can't see how we could help our users by providing yet another (probably imperfect!) logger implementation.

@B3zaleel could you please explain?

**Comment by alexreg** [comment]
I agree with @ForNeVeR on this. Logging isn't really something that should even be part of a library like this, in my view, let alone our own implementation.

**Comment by Happypig375** [comment]
And it is buggy. Why is the `LoggedErrors` field `static`?

**Comment by ForNeVeR** [comment]
Closed with #148.

**Pull request closed without merging**
