### PR TITLE
[WIP] Port to Avalonia

### PR DESCRIPTION
**Pull request by ForNeVeR**
Still very work-in-progress.

**Notes from the author:**
- [ ] Custom fonts are not working (math symbols are not working)
- [ ] Positions of the formula symbols are incorrect
- [ ] Project Properties removed as interrupting build

**Notes from me:**

We definitely don't want to remove WPF code, and we want Avalonia and WPF to coexist in our project, so the users could choose the UI framework they prefer. We'll need to put WPF code back, and extract Avalonia-specific parts from the main code base.

### CODE REVIEW

**Comment by alexreg** [comment]
A good start!

Once this is done, a rename of the project is probably in order. Something that conveys it's a generic maths rendering library... or alternatively a more innovative name, only loosely connected to its purpose.

**Comment by ahopper** [comment]
Just wondered if there was any plan to take this forward.  Avalonia now supports font embedding so that should help.

**Comment by alexreg** [comment]
@ahopper Not much progress I believe. @ForNeVeR doesn't have as much time these days, I think (though he should correct me if I'm wrong)... so if you want to take up this project, that would be great. I'm sure one of us could review.

**Comment by ahopper** [comment]
@alexreg I've had a quick play and with the latest Avalonia and a couple of tweaks the basics seem to work
image
I'm not sure what to do with this next.  I don't have the time right now to properly reintegrate into the wpf stuff. I also noticed some mention of combining with CSharpMath which I guess might take a different approach to avalonis integration, is this likely?

**Comment by alexreg** [comment]
@ahopper The unification with CSharpMath will only be at the level of atoms, at least initially, I believe. Anyway, good work there. If you can eventually create two different rendering/front-end projects, one for WPF and one for Avalonia, that would be ideal.

**Comment by ahopper** [comment]
I've put a first cut of combining the wpf and Avalonia code here https://github.com/ahopper/wpf-math/tree/avalonia-wpf-combined.
I have left the wpf code untouched and put anything that could be shared without modifying in a shared project. It is based on the current wpfmath.
The Avalonia version is more like the wpf version than this pr.
Obviously very much more code can be shared with some tweaking of the wpf code.
Before I go any further does this approach seem sensible?

**Comment by ForNeVeR** [comment]
@ahopper yes your approach looks pretty great. We definitely will need more unification between WPF and Avalonia code bases, but that's very good first steps.

I believe we could merge some of your code whenever you think it's in a good state, and maybe publish a separate experimental package with Avalonia stuff. After that we'll be able gradually unify the code (e.g. extract the things we can't share between WPF and Avalonia, and merge/deduplicate everything else). That will break a lot of stuff in that _experimental_ Avalonia package in the new versions, but that'll be okay I guess.

**Comment by ForNeVeR** [comment]
@victm thank you much for your contribution. It has been moved forward with #175 (and I've done my best to preserve the credits to you in the updated commit). Check #17 if you want to follow the Avalonia development in WPF-Math.

**Pull request closed without merging**
