### PR TITLE
implement CommandParser

### PR DESCRIPTION
**Pull request by rennmaus-coder**
Implemented A Begin CommandParser which parses until the next \end. Doesn't support nested environments.
Should I execlude the other files (fonts and images)?

## TODO[F]
- [x] Add a test.
- [x] Support nested environments.
- [x] More tests:
  - [x] test for `\pmatrix` nested inside of a `\begin{pmatrix}`,
  - [x] tests for every corner case across the code.
- [x] Investigate an example app failure: `\begin{pmatrix}{line 1}{line 2}\end{}`.
- [x] Roll back the changes in `NonRecursiveEnvironment`.
- [x] Documentation:
  - [x] doc-comments,
  - [x] user manual,
  - [x] changelog.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
At least, I think I know the source of changes in the `.ttf` and `.png` files. This was a misconfiguration of `.gitattributes`. I have fixed it in #327, but I guess I really need to cherry-pick that onto `master`.

Don't worry about that, I'll fix it in your branch myself.

**Comment by ForNeVeR** [comment]
Now, having the binary files' issue resolved, I am ready to take a look at the code for real. Sorry, it takes some time, because I am usually looking at the PRs at night or on weekends.

**Comment by rennmaus-coder** [comment]
No problem, thanks for looking at it! 👍

**Comment by ForNeVeR** [comment]
Ok, your solution works (but generates exceptions sometimes, I'll investigate), but I think a more complete fix is possible. I'll work on your branch a bit.

**Comment by rennmaus-coder** [comment]
Sure, if you want me to do anything let me know

**Review by ForNeVeR — APPROVED** [review]
Thanks for help!

**Pull request merged**
