### PR TITLE
Fixed crash on empty square root

### PR DESCRIPTION
**Pull request by sskodje**
\sqrt{} resulted in a CTD. This should fix it.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
I am sorry for the delay, will review that now.

**Comment by ForNeVeR** [comment]
@sskodje, thank you! I've merged your PR.

I've added a unit test for the failing case; please consider adding such tests yourself next time (but always feel free to ask for help!)

**Comment by ForNeVeR** [comment]
@sskodje also please note that I have no plans to publish a new release in the next few weeks. But in case you need the fixed version of WPF-Math to be published to NuGet, just ping me. I could publish a new version out-of-schedule if it's necessary for our users.

**Comment by sskodje** [comment]
No that's quite alright. I have forked and is using that atm, as i'm doing some other changes as well. I'll remember about the unit tests if i make more pull requests:)

**Pull request merged**
